# Run pipeline whenever a commit or tag is pushed
trigger:
  branches:
    include:
    - '*'
  tags:
    include: 
    - '*'

# Run pipeline whenever a PR is raised
pr:
  branches:
    include:
    - '*'

# Run pipeline everyday. Azure DevOps schedules follow UTC
# We build master on daily
schedules:
- cron: "0 14 * * *" # 00:00 AEST is 14:00 UTC
  displayName: 'Daily Build'
  branches:
    include:
    - master

variables:
  BuildConfiguration: release

pool:
  name: Hosted VS2017

steps:

- task: DotNetCoreCLI@2
  displayName: DotNet Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: |
      tests/**/*.csproj
      arguments: '--collect "Code coverage"


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True



- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'



